In [14]:
import numpy as np 
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.model_selection import train_test_split

df = sns.load_dataset("titanic")

df.fillna({
    "age":df.age.mean()
}, inplace = True)

model1 = LogisticRegression()
model2 = DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(df[["age","pclass"]], df["pclass"])

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)

y_pred1 = model1.predict(X_test)
y_pred2 = model2.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix

print(accuracy_score(y_test, y_pred1))
accuracy_score(y_test, y_pred2)

pd.DataFrame(confusion_matrix(y_pred1, y_test))
print(confusion_matrix(y_pred1, y_test))

1.0
[[ 50   0   0]
 [  0  47   0]
 [  0   0 126]]
